spring.application.name=NOTIFICATION-SERVICE

#server.port=8085

spring.config.import=optional:configserver:http://localhost:8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true


#eureka.instance.lease-renewal-interval-in-seconds=5
#eureka.instance.lease-expiration-duration-in-seconds=10
#spring.cloud.loadbalancer.retry.enabled=true
#
#spring.cloud.gateway.default-filters[1].name=Retry
#spring.cloud.gateway.default-filters[1].args.retries=3
#
#
## EMAIL CONFIG
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#
#spring.mail.username=your_email@gmail.com
#spring.mail.password=app_password
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## RABBITMQ CONFIG
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest